// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/30/2026, 9:29:55 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/ashminaik/Desktop/stt-web-app/nuxt-ui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ashminaik/Desktop/stt-web-app/nuxt-ui/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ashminaik/Desktop/stt-web-app/nuxt-ui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ashminaik/Desktop/stt-web-app/nuxt-ui/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ashminaik/Desktop/stt-web-app/nuxt-ui/plugins/**/*.{js,ts,mjs}","/Users/ashminaik/Desktop/stt-web-app/nuxt-ui/composables/**/*.{js,ts,mjs}","/Users/ashminaik/Desktop/stt-web-app/nuxt-ui/utils/**/*.{js,ts,mjs}","/Users/ashminaik/Desktop/stt-web-app/nuxt-ui/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ashminaik/Desktop/stt-web-app/nuxt-ui/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ashminaik/Desktop/stt-web-app/nuxt-ui/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;